=== Maltrix147/Studium/Semester_3/Datenmanagement/XML11_BU/beispiele/kap03/externAufgabe3.dtd
<!ELEMENT seminar (Ziel, Ort, Datum, Zeitplan+, Seminarleiter,Teilnehmer+,Person+)>
    <!ELEMENT Ziel (#PCDATA)>
    <!ELEMENT Datum (#PCDATA)>
    <!ELEMENT Ort (#PCDATA)>
    <!ELEMENT Seminarleiter (#PCDATA)>
    <!ELEMENT Zeitplan (ab9Uhr, ab13Uhr, ende)>
        <!ELEMENT ab9Uhr (Thema+)>
            <!ELEMENT Thema (#PCDATA)>
        <!ELEMENT ab13Uhr (Thema+)>
        <!ELEMENT ende (#PCDATA)>
    <!ELEMENT Teilnehmer (Person+)>
        <!ELEMENT Person (anrede, name, Vorname)>
            <!ELEMENT anrede (#PCDATA)>
            <!ELEMENT name (#PCDATA)>
            <!ELEMENT Vorname (#PCDATA)>

=== Maltrix147/Studium/Semester_3/Datenmanagement/XML11_BU/beispiele/kap03/Aufgabe3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seminar SYSTEM "externAufgabe3.dtd">
<seminar>
    <Ziel>Einführung in XML</Ziel>
    <Datum>02.04. - 06.04.</Datum>
    <Ort>XML-Stadt</Ort>
    <Seminarleiter>Herr Hans Hauser</Seminarleiter>
    <Zeitplan>
        <ab9Uhr>
            <Thema>Überblick</Thema>
            <Thema>XHTML</Thema>
            <Thema>XML-Struktur</Thema>
        </ab9Uhr>
        <ab13Uhr>
            <Thema>DTD Entwickeln</Thema>
            <Thema>Darstellung von XML mit XSL</Thema>
        </ab13Uhr>
        <ende>17Uhr</ende>
    </Zeitplan>
    <Teilnehmer>
        <Person anrede="Herr">
            <name>Rabicht</name>
            <Vorname>Rolf</Vorname>
        </Person>
        <Person anrede="Frau">
            <name>Sieghaar</name>
            <Vorname>Siegrund</Vorname>
        </Person>
        <Person anrede="Frau">
            <name>Landmann</name>
            <Vorname>Linda</Vorname>
        </Person>
        <Person anrede="Herr">
            <name>Brahms</name>
            <Vorname>Bruno</Vorname>
        </Person>
    </Teilnehmer>
</seminar>
