=== Maltrix147/Studium/Semester_3/Datenmanagement/XML11_BU/beispiele/kap03/Klausur.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Orte">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ort">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:integer"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="Mensch" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:integer"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="vorname" type="xs:string"/>
                                        <xs:element name="Gehalt" type="xs:decimal"/>
                                        <xs:element name="idOrt" type="xs:integer"/>
                                        <xs:element name="Kauf" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="idMensch" type="xs:integer"/>
                                                    <xs:element name="anzahl" type="xs:integer"/>
                                                    <xs:element name="bez" type="xs:string"/>
                                                    <xs:element name="preis" type="xs:decimal"/>
                                                    <xs:element name="Gesamt" type="xs:decimal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Maltrix147/Studium/Semester_3/Datenmanagement/XML11_BU/beispiele/kap03/klausur.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Orte xsi:noNamespaceSchemaLocation="Klausur.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Orte>
    <Ort>
        <id>1</id>
        <name>Neustadt</name>
        <Mensch>
            <id>1</id>
            <name>Holzflos</name>
            <vorname>Hugo</vorname>
            <Gehalt>234.56</Gehalt>
            <idOrt>1</idOrt>
            <Kauf>
                <idMensch>1</idMensch>
                <anzahl>3</anzahl>
                <bez>Hemd</bez>
                <preis>12.99</preis>
                <Gesamt>38.97</Gesamt>
            </Kauf>
            <Kauf>
                <idMensch>1</idMensch>
                <anzahl>9</anzahl>
                <bez>Hemd</bez>
                <preis>12.99</preis>
                <Gesamt>116.91</Gesamt>
            </Kauf>
        </Mensch>
    </Ort>
</Orte>
