=== Maltrix147/Studium/Semester_3/Datenmanagement/XML11_BU/beispiele/kap03/Uebung2.dtd
<!ELEMENT Seminar (Name, Datum, Ort, Vormittags, Nachmittags, Ende, Personen)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Datum (#PCDATA)>
<!ELEMENT Ort (#PCDATA)>
<!ELEMENT Vormittags (Thema)>
<!ATTLIST Vormittags Zeit>
<!ELEMENT Nachmittags (Thema)>
<!ELEMENT Thema (#PCDATA)>
<!ELEMENT Ende (#PCDATA)>
<!ELEMENT Personen (Leiter, Teilnehmer)>
<!ELEMENT Leiter (Vorname, Nachname)>
<!ELEMENT Vorname (#PCDATA)>
<!ELEMENT Nachname (#PCDATA)>
<!ELEMENT Teilnehmer (Person+)>
<!ELEMENT Person (Vorname, Nachname)>

=== Maltrix147/Studium/Semester_3/Datenmanagement/XML11_BU/beispiele/kap03/uebung2.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<!DOCTYPE Seminar SYSTEM "uebung2.dtd">
<Seminar>
    <Name>Einfuehrung in XML</Name>
    <Datum>2.4-6.4.</Datum>
    <Ort>Stadt</Ort>
    <Vormittags Zeit="ab9Uhr">
        <Thema>Ueberblick</Thema>
        <Thema>XML</Thema>
        <Thema>Struktur</Thema>
    </Vormittags>
    <Nachmittags Zeit="ab13Uhr">
        <Thema>XSL</Thema>
        <Thema>DTD</Thema>
    </Nachmittags>
    <Ende Zeit="bis17Uhr" />
    <Personen>
        <Leiter>
            <Vorname>Hans</Vorname>
            <Nachname>Hauser</Nachname>
        </Leiter>
        <Teilnehmer>
            <Person>
                <Vorname>Hans</Vorname>
                <Nachname>Hauser</Nachname>
            </Person>
            <Person>
                <Vorname>Hans</Vorname>
                <Nachname>Hauser</Nachname>
            </Person>
        </Teilnehmer>
    </Personen>
</Seminar>
