<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<!DOCTYPE MUSIKSAMMLUNG [
<!ELEMENT MUSIKSAMMLUNG (ALBUM+)>
<!ELEMENT ALBUM (AUTOR, (INTERPRET | GRUPPE)+,
                 TITEL, LIED*)>
<!ATTLIST ALBUM typ (CD | MP3 | Vinyl | MC) "MP3">
  <!ELEMENT AUTOR     (#PCDATA)>
  <!ELEMENT INTERPRET (#PCDATA)>
  <!ELEMENT GRUPPE    (#PCDATA)>
  <!ELEMENT TITEL     (#PCDATA)>
  <!ELEMENT LIED      (#PCDATA)>  ]>
<MUSIKSAMMLUNG>
  <ALBUM>
    <AUTOR></AUTOR>
    <INTERPRET></INTERPRET>
    <TITEL></TITEL>
    <LIED></LIED>
  </ALBUM>
</MUSIKSAMMLUNG>
