=== Maltrix147/Studium/Semester_3/Datenmanagement/XML11_BU/beispiele/kap08/group.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:group name="AdressenGruppe">
		<xs:sequence>
			<xs:element name="Strasse" type="xs:string"/>
			<xs:element name="Ort" type="xs:string"/>
			<xs:element name="PLZ" type="xs:integer"/>
		</xs:sequence>
	</xs:group>
	<xs:element name="Bestellung" type="BestellungTyp"/>
	<xs:complexType name="BestellungTyp">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Lieferanschrift">
				<xs:complexType>
					<xs:group ref="AdressenGruppe"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Rechnungsanschrift">
				<xs:complexType>
					<xs:group ref="AdressenGruppe"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Maltrix147/Studium/Semester_3/Datenmanagement/XML11_BU/beispiele/kap08/group.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Bestellung xsi:noNamespaceSchemaLocation="group.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Name>Herbert Hagedorn</Name>
	<Lieferanschrift>
		<Strasse>Hasenweg 13</Strasse>
		<Ort>Frankfurt/Main</Ort>
		<PLZ>60000</PLZ>
	</Lieferanschrift>
	<Rechnungsanschrift>
		<Strasse>Hauptstrasse 24</Strasse>
		<Ort>Hannover</Ort>
		<PLZ>20000</PLZ>
	</Rechnungsanschrift>
</Bestellung>
